---
version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(deps-actions)
    labels: [deps, ci]
    groups:
      gha-minor-and-patch:
        update-types: [minor, patch]
  # Python (pip)
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(deps-pip)
    labels: [deps, python, prod]
    groups:
      pip-runtime-minor-patch:
        patterns: ['*']
        update-types: [minor, patch]
  # npm PROD (dependencies)
  - package-ecosystem: npm
    directory: /app/frontend
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    versioning-strategy: increase
    commit-message:
      prefix: chore(deps-npm:prod)
    labels: [deps, js, ts, frontend, prod]
    allow:
      - dependency-type: production
    groups:
      npm-prod-minor-and-patch:
        update-types: [minor, patch]
  # npm DEV (devDependencies)
  - package-ecosystem: npm
    directory: /app/frontend
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    versioning-strategy: increase
    commit-message:
      prefix: chore(deps-npm:dev)
    labels: [deps, js, ts, frontend, dev]
    allow:
      - dependency-type: development
    groups:
      npm-dev-minor-and-patch:
        update-types: [minor, patch]
      npm-dev-major:
        update-types: [major]
